GET https://render-idat.onrender.com/
###
GET https://render-idat.onrender.com/demo/all
###
POST https://render-idat.onrender.com/demo/add
Content-Type: application/x-www-form-urlencoded

name=Juana&email=Juana@idat.edu.pe
###
DELETE https://render-idat.onrender.com/demo/del
Content-Type: application/x-www-form-urlencoded

id=1